### ISSUE TITLE
WIP rewrite

### ISSUE THREAD

**Issue by willwade** [AceCentre/MorseWriter#31]
This is happening in branch pynput - the name is ironic as its no longer using that! 

**To-Do**

- [x]  ChangeLayout isnt working. The refactor and opening/hiding of windows is a headache. see def init() around 663 - I think we need to pass self in at the end.. 
- [x]  Bring back sound for end of character #34
- [x] Check mouse mode.. I dont think I have that tied up right
- [x] Equally check all other modes. And check all keycodes possible. Remove some that dont
- [x]  Work out why original had smaller config window. Maybe we never released the latest and this bigger config is what I wanted to do?

- [x] Dont allow same keys to be used for keyOne, KeyTwo, keyThree #35 
- [x] #32 
- [x] New logo. Make sure used throughout. 
- [x] create installer for windows. 
- [ ] create installer for mac 
- [ ] create speak mode. 
- [ ] allow one mode. Where it speaks letters on entry and the. Word predictions. 

**Maybe**

- [ ] #33 

**Done**

- [x] #28
- [x]  #27 
- [x] #29    
- [x] Migrated from win32 and pressage C libraries. Now far far easier to build. BUT still windows only because the hook wont work on Mac.

**Comment by willwade** [comment]
See https://chatgpt.com/share/62341843-0f84-46da-97af-f03e0d756815 for a lot of the obvious ones. The first thing it discusses I’m pretty sure won’t work
